language: java
jdk: oraclejdk8
before_install:
- chmod +x gradlew
before_deploy:
- chmod ugo+x deploy.sh
script:
- bash ./gradlew clean build
- bash ./deploy.sh
env:
  global:
  - GH_REF: github.com/garystafford/microservice-docker-demo-user.git
  - secure: pLNTdFLd2L3MK+Zr7xGpOHE71VVVgiRP95ekFSyYajeLIacqfIzTdrjekc3E9Em84YfUezAP5M8LPGPVOHrb6wl+svfLCM4Th7IZ4RSfAeAvbpT6kbFyz5zX6rJCehDgwOYqlRR7xPd6F+pVtUIRB7VqW/xbQNkt1JgsxqADFCWo/oZOJFGge5nHg3RWV7LnVWaKKOH8kaNuXc0vZd3B4CHAq7TG3rxoDGGaV4fT6apwx1bNp8yX2T370AXJBWd91dSzL1T5/e4bffOS/7nBrBmwd356Uf8Cj3fH/k97X12zOKw67luxcIjJLv6RWN306Z44NCMjwcB0uCfkfHql7aJiLnwxn4x6SFh7+9KWZKJ+A793+nHHBBLEaJQIoWARmvbIJMhIvxEZkMLXA8ujaO5Ms5VLbZugtDsEABy2/Cs77jG+CSGaCXHGMzF8KHzHcmNESbPOEfYBvxusCIT27sEd64o8wBOeScBISkl8rxYp12owjVYXNy4ViM8ZonLMIiQmj/Xvl7XQ7dBk3weW2oNCRQzZGrAzc7mrwQ1PBNuN9EU/DnkMvfBHnNzGE0XDNTkIvHMSHjZYJWKmbkjFHMO1pJwDDq9obIX9OY/Nye2SS2rj4IKb4X7FkEwM2mljxmvwxAVrfO9iPsjXNmiurlfA/hxcwasbDPfhv07OR0I=
notifications:
  slack:
    secure: lQ9wlH21js1OMwStoDjMjPc/G1zdfE0UdbiR1kVunJ4FIowlLW6JHdU1186Jz8ouXoyzXhpT3NMj617QLm4alznBW0ndreieS9sybjhJS1gMNtLKJR9O2LXAwCWH+tQkXGDVOLygSvR/2Xlom+lFHr5Xg/IgWcGB3CO2pIIML3dOCojUstwKhoYSoxO8LpMFsZtXD+qpKeHTbVF7QSRXb3ghIYC15MNOs508z8Ed7vip5iNn/itUzSPsH1thBY2f80Fq4bh6WvQhvo2SsaUa01lw+btMbXA2FCQ3jAhZZG1SauuWXpEhgQ3IfOuWJRuDXY/kX+Q+dYjGqIH9qTT25svGEeMnUykfW3m1UrPe2G+9tJ9nyfWNxePlm4gWlzZhGha04UxVwBi+5DqiiS231ztDMQ/mWwp2Z6kUAgu97Om5lRov3zDXyI03vKCmiCTJx7NVLOiiWIqNqLth/ALfcdjtnHnwIH6bP+u26EmtHt5WjTP+PFbqIsFcLLtEQRlsFhUPhJY/2xO+jQrt0prYB0LC8hO9jDct9VIgju3D2y2BenecewV/GrHMVjhXxYbsW1gNAckZ34ZFUkfMRJegpCt81/vhhkrgJPmBespONROrcPI2ILSJTAXbUuwRIZ8Dcrnmg8/P/MbNsAIxrY4jH7RHV1JWM7/aoFaLsCUpj00=
